### ISSUE TITLE
Throttle 0.2.7 requires Java 9

### ISSUE THREAD

**Issue by bp-alex** [client-side/throttle#3]
We've been using 0.2.6 for some time and noticed the 0.2.7 release. As per [Semantic Versioning](https://semver.org/) we assumed this was a patch release and referenced the new version. Unfortunately this release requires Java 9.

Would it be possible to release a new version that uses Java 8 bytecode?

**Comment by jpe42** [comment]
Ah, sorry, I wasn't thinking.  There were no actual source code changes, only gradle/travisci/test changes.  I only released it because it was an easy way to make sure the pipeline was still working.  I scanned through this recent [Gradle blog post about multi release jars](https://blog.gradle.org/mrjars), but it isn't something I have time to dive into and maintain.  I've updated the README with a comment about the last supported Java 8 version and will properly bump the minor or major version if anything needs to be released again.

**Comment by bp-alex** [comment]
No worries, thanks for all your work on this great library.
